default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false

development:
  <<: *default
  database: api_dev
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  <<: *default
  database: api_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

staging:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>

production:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
